application:
  port: 3000
  host: "127.0.0.1"

database:
  username: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
  database_name: "zedauth"

jwt:
  secret: "your-secret-key-here"
  expiration: 3600 # 1 hour in seconds 